apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dapr-ingress  
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - calculator.local.com
    secretName: calculator-local-tls  
  - hosts:
      - rest.local.com
    secretName: rest-local-tls  
  - hosts:
      - echo.local.com
    secretName: echo-local-tls  
  - hosts:
      - ingress.local.com
    secretName: ingress-local-tls  
  - hosts:
      - seq.local.com
    secretName: seq-local-tls   
  - hosts:
      - zipkin.local.com
    secretName: zipkin-local-tls   
  - hosts:
      - redis.local.com
    secretName: redis-local-tls   
  - hosts:
      - rabbitmq.local.com
    secretName: rabbitmq-local-tls   
  - hosts:
      - react.local.com
    secretName: react-local-tls   
  - hosts:
      - redisinsight.local.com
    secretName: redisinsight-local-tls   
  rules:
  - host: calculator.local.com
    http:
      paths:      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: calculator-front-end
            port: 
              number: 8080  
  - host: rest.local.com
    http:
      paths:      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rest-server-service
            port: 
              number: 8080  
  - host: echo.local.com
    http:
      paths:      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo-server-service
            port: 
              number: 8088  
  - host: ingress.local.com
    http:
      paths:      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dapr-client-service
            port: 
              number: 8083  
  - host: seq.local.com
    http:
      paths:      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: seq-service
            port: 
              number: 80  
  - host: zipkin.local.com
    http:
      paths:      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zipkin-service
            port: 
              number: 9411  
  - host: redis.local.com
    http:
      paths:      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redis-commander
            port: 
              number: 8081  
  - host: rabbitmq.local.com
    http:
      paths:      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port: 
              number: 15672  
  - host: react.local.com
    http:
      paths:      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-form
            port: 
              number: 80  
  - host: redisinsight.local.com
    http:
      paths:      
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redisinsight-service
            port: 
              number: 8001


