
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-server
  labels:
    app: dapr-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-server
  template:
    metadata:
      labels:
        app: dapr-server
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "catalog"
        dapr.io/app-port: "80"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: dapr_server
        image: tmather99/dapr_server
        ports:
        - containerPort: 8081
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"  
        env:
        - name: SEQ_SERVER_URL
          value: "http://seq-service"        
        - name: SECRET_STORE_NAME
          value: "kubernetes"
        - name: ASPNETCORE_URLS
          value: "http://*:8081"        

---
apiVersion: v1
kind: Service
metadata:
  name: dapr-server-service
spec:
  selector:
    app: dapr-server-app  
  type: ClusterIP  
  ports:
    - protocol: TCP 
      port: 8081
      targetPort: 8081
