apiVersion: apps/v1
kind: Deployment
metadata:
  name: addapp
  labels:
    app: add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add
  template:
    metadata:
      labels:
        app: add
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "addapp"
        dapr.io/app-port: "6000"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: add
        image: tmather99/distributed-calculator-go:latest-linux-amd64
        env:
        - name: APP_PORT
          value: "6000"
        ports:
        - containerPort: 6000
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"  
        imagePullPolicy: Always
