apiVersion: apps/v1
kind: Deployment
metadata:
  name: divideapp
  labels:
    app: divide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: divide
  template:
    metadata:
      labels:
        app: divide
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "divideapp"
        dapr.io/app-port: "4000"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: divide
        image: tmather99/distributed-calculator-node:latest-linux-amd64
        env:
        - name: APP_PORT
          value: "4000"
        ports:
        - containerPort: 4000
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"  
        imagePullPolicy: Always
